In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('ml-zoomcamp-01-intro-homework')
jovian.set_colab_id('1QvVleKfxzyu4Vwg4G6bQmEfTIxGGDIty')

     |████████████████████████████████| 68 kB 4.3 MB/s 


# ml-zoomcamp-01-intro-homework

Use the "Run" button to execute the code.

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [4]:
import pandas as pd
import numpy as np


# Downloading the data

In [ ]:
car_price_df = pd.read_csv()

# Question 1
What's the version of NumPy that you installed?

In [6]:
print(np.__version__)

1.21.6


In [7]:
# Execute this to save new versions of the notebook
jovian.commit(project="ml-zoomcamp-01-intro-homework")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/pknayak0707-job/ml-zoomcamp-01-intro-homework


'https://jovian.ai/pknayak0707-job/ml-zoomcamp-01-intro-homework'

# Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

    16
    6572
    11914
    18990


In [51]:
car_price_df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [52]:
car_price_df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

In [53]:
print(car_price_df.shape[0])

11914


# Question 3

In [54]:
car_price_df['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Question 4

In [55]:
len(car_price_df[car_price_df['Make']=='Audi']['Model'].unique())

34

# Question 5

In [56]:
#df2.isnull().any(axis=1)
missing_val_cond = car_price_df.isnull().any(axis=0)
type(missing_val_cond)

pandas.core.series.Series

In [57]:
# truth_table = df.isnull()
# conclusive_truth_table = truth_table.any(axis='columns')
# df[conclusive_truth_table]
condition_null_values = missing_val_cond[missing_val_cond==True]
missing_val_columns = condition_null_values.index.to_list()
print(len(missing_val_columns),missing_val_columns )

5 ['Engine Fuel Type', 'Engine HP', 'Engine Cylinders', 'Number of Doors', 'Market Category']


# Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

> Hint: refer to existing mode and median functions to complete the task.
> 
- Yes
- No

In [59]:
old_median_value = car_price_df['Engine Cylinders'].median()
old_median_value

6.0

In [60]:
car_price_df['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [61]:
car_price_df['Engine Cylinders'] =  car_price_df['Engine Cylinders'].fillna(car_price_df['Engine Cylinders'].mode())

In [62]:
new_median_value = car_price_df['Engine Cylinders'].median()
new_median_value

6.0

In [64]:
if(new_median_value==old_median_value):
  print('The new and old median value are Equal')
else:
  print('The new and old median value are not Equal')

The new and old median value are Equal


# Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the value of the first element of `w`?

> 
> 

> Note: You just implemented linear regression. We'll talk about it in the next lesson.
> 
- 0.0723
- 4.5949
- 31.6537
- 63.5643

In [79]:
list_of_cars = list(car_price_df['Make'].unique())
list_of_cars.index('Lotus'), len(list_of_cars)

(41, 48)

In [81]:
# 1.Select all the "Lotus" cars from the dataset.
lotus_cars = car_price_df[car_price_df['Make']=='Lotus']
lotus_cars.shape

(29, 16)

In [83]:
# 2. Select only columns "Engine HP", "Engine Cylinders".
specific_col_lotus_cars = lotus_cars[['Engine HP', 'Engine Cylinders']]
specific_col_lotus_cars.shape

(29, 2)

In [85]:
# 3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
specific_col_lotus_cars.drop_duplicates(inplace=True)
specific_col_lotus_cars.shape

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


(9, 2)

In [86]:
specific_col_lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [97]:
numpy_array = specific_col_lotus_cars.to_numpy()
numpy_array

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [100]:
# 4. Get the underlying NumPy array. Let's call it `X`.
X = numpy_array
X,X.shape, X.T, X.T.shape

(array([[189.,   4.],
        [218.,   4.],
        [217.,   4.],
        [350.,   8.],
        [400.,   6.],
        [276.,   6.],
        [345.,   6.],
        [257.,   4.],
        [240.,   4.]]),
 (9, 2),
 array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
        [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]]),
 (2, 9))

In [101]:
# 5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
np.matmul(X.T,X), np.dot(X.T,X) # exactly the same
XTX = np.matmul(X.T,X)
XTX,XTX.shape 

(array([[7.31684e+05, 1.34100e+04],
        [1.34100e+04, 2.52000e+02]]), (2, 2))

In [102]:
# 6. Invert `XTX`.
inv_XTX = np.linalg.inv(XTX)
inv_XTX, inv_XTX.shape

(array([[ 5.53084235e-05, -2.94319825e-03],
        [-2.94319825e-03,  1.60588447e-01]]), (2, 2))

In [103]:
# 7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
list_y_values = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = np.array(list_y_values)
y, y.shape

(array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800]), (9,))

In [104]:
# 8. Multiply the inverse of `XTX` with the transpose of `X`, ...
inv_XTX_x_XT = np.matmul(inv_XTX,X.T)
inv_XTX_x_XT, inv_XTX_x_XT.shape

(array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
         -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
          1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
        [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
          2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
         -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]]), (2, 9))

In [105]:
#.. .and then multiply the result by `y`. Call the result `w`.
w = np.matmul(inv_XTX_x_XT,y)
w, w.shape

(array([  4.59494481, -63.56432501]), (2,))

In [106]:
# 9. What's the value of the first element of `w`?
w[0]

4.594944810094551

In [107]:
# Execute this to save new versions of the notebook
jovian.commit(project="ml-zoomcamp-01-intro-homework")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/pknayak0707-job/ml-zoomcamp-01-intro-homework


'https://jovian.ai/pknayak0707-job/ml-zoomcamp-01-intro-homework'